### PR TITLE
Create admin2

### PR DESCRIPTION
**Pull request by selfup**
Was able to successfully display issues and stances by candidate id

Now we just need to add edit, and deletion functionality as well as progress bars for goals

BUNDLE after pulling :)

### CODE REVIEW

**Comment by jbrr** [comment]
Yeah, also slugs are made, but they aren't implemented yet. We can work on that tomorrow.

**Comment by selfup** [comment]
We can now edit candidate bio's as well as individual stances

**Comment by jbrr** [comment]
Yess! It works!! Let's remember to refactor `candidate_issues_controller`, it's pretty fat.

**Comment by roseak** [comment]
Still need to make sure that the flash errors are styled red.

**Pull request merged**
